language: node_js
sudo: false
services:
  - docker
node_js:
- '7'
cache:
  yarn: true
script:
- yarn build
- yarn run lint
- yarn test
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - bash ./scripts/build-docker-images.sh
  - bash ./scripts/generate-answers.sh
  - bash ./scripts/install-rancher.sh
  - bash ./scripts/deploy.sh
