language: node_js
sudo: false
services:
  - docker
node_js:
  - '7.10'
cache:
  yarn: true
env: DISPLAY=':99.0'
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - yarn build
  - yarn run lint
  - yarn test
  - yarn test:acceptance_local
after_success:
  - bash ./scripts/deploy.sh
before_script:
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - ./node_modules/.bin/selenium-standalone start &
