language: node_js
sudo: false
services:
  - docker
node_js:
  - '7.10'
cache:
  yarn: true
env: DISPLAY=':99.0'
script:
  - yarn build
  - yarn run lint
  - yarn test
  - yarn test:acceptance_local
after_success:
  - bash ./scripts/deploy.sh
before_install:
  - docker pull selenium/standalone-chrome:2.53.0
before_script:
  - docker run -d --net=host selenium/standalone-chrome:2.53.0
  - export DISPLAY=:99.0
  - chmod -R 777 src/__tests__/plugins/register-form/acceptance/output
  - sh -e /etc/init.d/xvfb start
  - sleep 10
