language: node_js
sudo: false
services:
  - docker
node_js:
  - '7'
cache:
  yarn: true
script:
  - yarn build
  - yarn run lint
  - yarn test
  - yarn test:acceptance_local
after_success:
  - bash ./scripts/deploy.sh
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "./node_modules/.bin/selenium start"
