language: node_js
sudo: true
services:
  - docker
node_js:
- '7.8.0'
cache:
  yarn: true
script:
- yarn build
- yarn run lint
- yarn test
- yarn test:acceptance_headless
after_success:
  - bash ./scripts/deploy.sh
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start