version: '2'
services:
  elasticsearch-updater-profiles:
    image: nhsuk/elasticsearch-updater:0.3.2
    environment:
      CHANGE_THRESHOLD: '0.96'
      ES_HOST: profiles-db-elastic
      ES_INDEX: profiles
      JSON_FILE_URL: https://nhsukgpdataetl.blob.core.windows.net/etl-output/gp-data-merged.json
      NODE_ENV: production
      UPDATE_SCHEDULE: ''
