version: '2'

services:

  register-with-a-gp:
    image: nhsuk/register-with-a-gp:${DOCKER_IMAGE_TAG}
    environment:
      NODE_ENV: production
      SESSION_SECRET: ${SESSION_SECRET}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      POSTCODE_API_KEY: ${POSTCODE_API_KEY}
      POSTCODE_API_HOST: ${POSTCODE_API_HOST}
    labels:
      traefik.enable: stack
      traefik.domain: ${TRAEFIK_DOMAIN}
      traefik.port: 3333
      io.rancher.container.pull_image: always