version: '2.1'
services:
  web:
    environment:
      ES_HOST: ${ES_HOST}
      ES_PORT: ${ES_PORT}
      NODE_ENV: 'development'

    build:
      context: .
      args:
        NODE_ENV: 'development'

    command: yarn run dev
    ports:
      - 3333:3333
    links:
      - profiles-db-elastic:es
    volumes:
      - .:/code
      - register-with-a-gp-node_modules:/code/node_modules

  elasticsearch-updater-profiles:
    image: nhsuk/elasticsearch-updater:0.3.2
    environment:
      CHANGE_THRESHOLD: '0.96'
      ES_HOST: profiles-db-elastic
      ES_INDEX: profiles
      JSON_FILE_URL: https://nhsukgpdataetl.blob.core.windows.net/etl-output/gp-data-merged.json
      NODE_ENV: production
      UPDATE_SCHEDULE: ''
    depends_on:
      profiles-db-elastic:
        condition: service_healthy
    links:
      - profiles-db-elastic

  profiles-db-elastic:
    image: nhsuk/profiles-db-elastic:0.3.0
    environment:
      bootstrap.memory_lock: 'true'
      xpack.monitoring.enabled: 'false'
      xpack.security.enabled: 'false'
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  register-with-a-gp-node_modules: